### ISSUE TITLE
Timer resetting after reaching 0:00

### ISSUE THREAD

**Issue by wojciechgizynski** [evanbrumley/spyfall#2]
The timer starts countdown from 8:00, but once 0:00 is reached it goes to 59:59 and starts counting down an entire hour. The label of the timer could change to "Time's up!" once at 0:00. I think it also would be a good idea to introduce a pop-up alert informing that time run out and/or a bell sound to announce that.

**Comment by evanbrumley** [comment]
The resetting problem should now be fixed - I forgot to put a floor on the time remaining, so it was trying to render negative values 0__o

I've also made the countdown timer flash a few times when the time runs out. A simple solution, but easy to implement and doesn't create any more work for my translators :-)
