### ISSUE TITLE
Question: Is this legal?

### ISSUE THREAD

**Issue by mikaelec** [evanbrumley/spyfall#31]
I was wondering if you are even allowed to make this app, based on a published board game? :)

**Comment by evanbrumley** [comment]
Hi Mikael,

The issue of copyright and trademarks as they relate to board games is quite complex. Game mechanics cannot be copyrighted, so as far as the basic functionality of the site goes, there's no problem. Trademarks are a different story - if Hobbyworld requested that I cease using the name "Spyfall" in the header, URL, repo etc, I would be obliged to do so (and would, happily).

On top of the legal issues, there's a moral take to consider as well - i.e. is it right to take someone else's board game and recreated it wholesale online? I'll leave that to you to decide, but this is one of the reasons I've limited the functionality of the site, kept it ad-free and used a very sparse design. Hobbyworld or Cryptozoic may want to enter the web/mobile space themselves at some point, and I want the market to be as open for them as it can be when they do. In the meantime, I hope the coverage this site received has generated at least a few physical sales for them :-)

Regards,

Evan

**Comment by mikaelec** [comment]
Great answer, thank you.
