### ISSUE TITLE
Meteor Free Hosting shutting down.

### ISSUE THREAD

**Issue by Maromarius** [evanbrumley/spyfall#36]
> Hi there,
> 
> Over the past three years, maintaining the free Meteor.com hosting service for 10,000s of apps has taken a big toll on our ability to move fast on other products. Now that reliable, pay-as-you-go Meteor hosting is available for everyone via Galaxy, we’re confident that Galaxy is a better home for your apps and will give everyone the chance to try it for free. As a result, we will retire the legacy Meteor.com free hosting service on March 25, 2016.
> 
> We know many of you have enjoyed the Meteor.com free hosting service. In a perfect world with infinite resources, we’d invest to keep this separate legacy infrastructure up and running. Unfortunately, delivering free Meteor app hosting has become extremely expensive and technically unsustainable. If there is a cost effective way to deliver free Meteor app hosting in the future, we may explore it but it’s not on our roadmap. For now, we’re 100% focused on making Galaxy the best deployment option for professional Meteor developers. 
> 
> How do I migrate my Meteor.com app to another hosting service?
> 
> Before March 25, 2016 12pm PDT, please migrate your app from the free Meteor.com hosting service to another app hosting platform to ensure continued availability of your app. You will also have until April 15, 2016 12pm PDT to retrieve data from your app’s Mongo database. Here are specific instructions on how to migrate your Meteor app as well as access your data from the Meteor.com free hosting service.
> 
> If you want stable, pay-as-you-go hosting for your Meteor app, we recommend using Galaxy (pricing starts at USD $0.035 per container hour). If you signup for a new Galaxy account and migrate your app by March 25, you’ll receive a $25 credit (use promo code MARCH25). This credit will provide a new home for your app at *.meteorapp.com and let you experience proven features that help developers build better Meteor apps. 
> If you’re only looking for free hosting, we recommend using a combination of free services from Heroku and MongoLab. Here are links to some community articles to help you get started:
> https://medium.com/@leonardykris/how-to-run-a-meteor-js-application-on-heroku-in-10-steps-7aceb12de234#.h34gmy8pb
> http://justmeteor.com/blog/deploy-to-production-on-heroku/
> You can also consult the Meteor Guide for other DIY deployment options.
> 
> Thanks for using Meteor and best of luck on your future projects.
> -Meteor Development Group

You must have read that email. What could be the hosting options?

**Comment by evanbrumley** [comment]
Hi Maromarius! I'm in the process of setting up a new home for Spyfall on Digitalocean. Super frustrating that we only get 2 weeks for the transition, and no word yet on whether they'll be providing redirects.

**Comment by evanbrumley** [comment]
Finally got around to updating the documentation today, now that everything has transitioned smoothly over to spyfall.crabhat.com.
