### ISSUE TITLE
Alien in the space station is a really stupid role

### ISSUE THREAD

**Issue by SarenCurrie** [evanbrumley/spyfall#38]
All they answer is "what is X" where X is what the question was about.

**Comment by GioBonvi** [comment]
It's up to you to decide how to answer a question. Using a bit of
imagination can help: for example you can imagine the space station not
exactly like the real ISS, but more like a Star Trekish rendezvous point
for human and aliens.

Il sab 9 lug 2016, 16:38 Saren Currie <notifications@github.com> ha scritto:

> All they answer is "what is X" where X is what the question was about.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/evanbrumley/spyfall/issues/38>, or mute the thread
> <https://github.com/notifications/unsubscribe/AMtwUia00uVXzogz4e6-vh1V-tF4NsoFks5qT7JKgaJpZM4JIoUW>
> .
>
-- 

Giorgio Bonvicini
bonvicini.giorgio@gmail.com
