### ISSUE TITLE
no game code found

### ISSUE THREAD

**Issue by jugina** [evanbrumley/spyfall#8]
Hello!

Me and my friends were trying to play Spyfall the other day, and we couldn't join each other using the given access code. It said: "Sorry, no game was found with the access code you provided!" where on the hosts device it was running and waiting for players. The whole site seems pretty straight forward, but is there something we're missing? 

If not, what could be the problem? 

Thanks for your reply in advance!

**Comment by jh0ker** [comment]
I had the same problem with my friends today, so I decided to upload the game to my own server (with the exception that the time limit is set to 1.5min times the amount of players, because we like it more).
In case this doesn't get fixed soon, you can use my mirror: http://spyfall.jhoeke.de/ 
Worked without any problems so far.

**Comment by evanbrumley** [comment]
Thanks for letting me know jugina. Node posted another video yesterday and it looks the site buckled a little under the pressure! I never imagined I'd end up with the site handling 10,000+ games daily 0__o

I've just done a hard reset, which seems to have fixed the issue for now. Moving forward I'm going to be making some improvements to the way games sync between devices, which I hope will prevent this happening again. In the meantime, please feel free to post another ticket if it reoccurs and I'll attempt to fix ASAP!

**Comment by GChearswat** [comment]
Haha, "I never imagined I'd end up with the site handling 10,000+ games daily 0__o" What a nice problem to have. Congrats!

**Comment by jugina** [comment]
I'm so greatful for this quick answer! I found out of your app on Node's channel as well. It seemed fun. I also read somewhere in the comments, that the app does not work with Android. Is that true?

Anyway, we'll try to give it a go tomorrow and if something goes bad, I'll let you know.
Thank you very much again!
